name: 'Dev.to Stats'
description: 'Pull stats about your Dev.to posts'
author: 'Josh Kasuboski'
inputs:
  apiKey:
    required: true
    description: 'API Key for Dev.to'
  outFile:
    required: true
    description: 'The file path to write the stats as json'
    default: 'dev-to-stats/stats.json'
runs:
  using: 'node12'
  main: 'dist/index.js'
